name: Create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gather facts
        id: facts
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install the dependencies
        run: ./docker-npm install
      - name: Build
        run: ./docker-npm run build
      - name: Package
        run: zip -r bowling-app_${{ steps.facts.outputs.SOURCE_TAG }}.zip ./build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: bowling-app_${{ steps.facts.outputs.SOURCE_TAG }}.zip