name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --no-cache --build-arg "UID=$(id -u)" --build-arg "GID=$(id -g)" -t bowling-app .
    - name: Creating the container
      run: docker create -t -v "$(pwd)":/app/opt --name bowling-test bowling-app run test
    - name: Running tests
      run: docker start -a bowling-test
