name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install the dependencies
      run: ./docker-npm install
    - name: Run the tests
      run: ./docker-npm run test
